### ISSUE TITLE
Unable to delete announcement

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/AnnouncementsPortlet#83]
**Describe the bug**
When attempting to delete an announcement, the user is greeted with the following message
>HTTP Status 405 - Request method 'GET' not supported

**To Reproduce**
1. Create create announcement
2. Attempt to delete announcement

**Expected behavior**
The announcement being deleted

**Comment by drewwills** [comment]
Good catch -- another one of those method-mismatches.

**Comment by bjagg** [comment]
Wrap deleteEntry link in treeEntries.tag with a form to change it from a GET to POST. Also style to retain original appearance.

Suggest use of:

```
<form action="${portlet action link}" method="post">
<button type="submit">
<a href="javascript:void(0);">link text</a>
</button>
</form>
```
